name = "SpmImageTycoonInstaller"
uuid = "306e248c-d22f-4909-81db-ed3c44a8c0e1"
authors = ["Alex Riss"]
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
PackageCompiler = "^2.1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
